const fs = require('fs');
const os = require('os');

const nodeName = process.env.NODE_NAME || 'Unknown';
const podName = os.hostname();
const targetDirectory = process.env.TARGET_DIR || '/etc';
const fileName = process.env.FILE_NAME || 'initdata.txt';
const content = `Node name ${nodeName} (generated by init POD ${podName})`;

fs.writeFile(`${targetDirectory}/${fileName}`, content, (err) => {
    if (err) {
        console.error('Error writing file:', err);
        process.exit(1);
    } else {
        console.log(`File saved to ${targetDirectory}/${fileName}`);
        process.exit(0);
    }
});
